<?php
require('view_func.php');
require('class.Baza.php');
require('mysql_config.php');
include('class.Country.php');
include('class.Player.php');
include('class.Team.php');
//include('class.Country.php');
?>